import type { Metadata } from "next"
import Link from "next/link"
import LegalPageShell, { LegalSection } from "@/components/legal/LegalPageShell"

export const metadata: Metadata = {
  title: "Terms of Service — Movie Clips",
  description: "Terms of Service for Movie Clips by Purple Merit",
  robots: { index: true, follow: true },
}

const EFFECTIVE_DATE = "August 11, 2026"
const CONTACT_EMAIL = "privacy@purplemerit.shop"

export default function TermsOfServicePage() {
  return (
    <LegalPageShell title="Terms of Service" effectiveDate={EFFECTIVE_DATE}>
      <LegalSection title="1. Agreement">
        <p>
          These Terms of Service (“Terms”) govern your access to and use of <strong>Movie Clips</strong> (also referred
          to as Clip AI), operated by <strong>Purple Merit</strong> (“we”, “us”, or “our”), available at{" "}
          <a href="https://vid-editor-tan.vercel.app">https://vid-editor-tan.vercel.app</a> (the “Service”).
        </p>
        <p>By creating an account or using the Service, you agree to these Terms and our <Link href="/privacy">Privacy Policy</Link>.</p>
      </LegalSection>

      <LegalSection title="2. The Service">
        <p>
          Movie Clips lets you upload or link long-form videos, split them into short clips, generate AI-assisted
          captions or summaries, optionally distribute clips to file hosts, and publish to connected platforms such as
          YouTube and Instagram.
        </p>
        <p>Features may change, and some capabilities depend on third-party APIs and your connected accounts.</p>
      </LegalSection>

      <LegalSection title="3. Accounts">
        <ul>
          <li>You must provide accurate registration information and keep your credentials secure.</li>
          <li>You are responsible for activity under your account.</li>
          <li>You must be old enough to form a binding contract in your jurisdiction (and at least 13 years old).</li>
        </ul>
      </LegalSection>

      <LegalSection title="4. Your content and license">
        <p>
          You retain ownership of videos and other content you submit (“User Content”). By submitting User Content, you
          grant us a worldwide, non-exclusive license to host, process, transcode, store, display, and transmit that
          content solely to operate and improve the Service (including AI processing and publishing you request).
        </p>
        <p>
          You represent that you have all rights needed to upload and process User Content and to publish it to any
          platforms you connect.
        </p>
      </LegalSection>

      <LegalSection title="5. Acceptable use">
        <p>You agree not to:</p>
        <ul>
          <li>Upload or publish content you do not have rights to use</li>
          <li>Violate copyright, trademark, privacy, publicity, or other laws</li>
          <li>Upload malware, attempt unauthorized access, or disrupt the Service</li>
          <li>Use the Service for spam, scams, harassment, or illegal activity</li>
          <li>Circumvent rate limits, security controls, or platform policies of YouTube, Meta/Instagram, or file hosts</li>
        </ul>
        <p>We may suspend or terminate accounts that violate these Terms.</p>
      </LegalSection>

      <LegalSection title="6. Third-party platforms">
        <p>
          Publishing to YouTube, Instagram, or file hosts is subject to those providers’ terms and policies. We are not
          responsible for their availability, content moderation, account bans, or changes to their APIs.
        </p>
        <p>
          OAuth connections are optional. You can revoke access at any time through the Service or your Google/Meta
          account settings.
        </p>
      </LegalSection>

      <LegalSection title="7. AI-generated output">
        <p>
          Captions and summaries may be generated by AI and can be inaccurate or incomplete. You are responsible for
          reviewing output before publishing.
        </p>
      </LegalSection>

      <LegalSection title="8. Fees">
        <p>
          The Service may be offered free or with paid features in the future. If fees apply, we will describe them
          before you are charged.
        </p>
      </LegalSection>

      <LegalSection title="9. Disclaimer of warranties">
        <p>
          THE SERVICE IS PROVIDED “AS IS” AND “AS AVAILABLE” WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED,
          INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. We do not guarantee
          uninterrupted or error-free operation, or that processing/publishing will succeed in every case.
        </p>
      </LegalSection>

      <LegalSection title="10. Limitation of liability">
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, PURPLE MERIT AND ITS AFFILIATES WILL NOT BE LIABLE FOR INDIRECT,
          INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, OR GOODWILL, ARISING
          FROM YOUR USE OF THE SERVICE. OUR TOTAL LIABILITY FOR ANY CLAIM RELATING TO THE SERVICE WILL NOT EXCEED THE
          AMOUNT YOU PAID US (IF ANY) IN THE 12 MONTHS BEFORE THE CLAIM.
        </p>
      </LegalSection>

      <LegalSection title="11. Indemnity">
        <p>
          You agree to indemnify and hold harmless Purple Merit from claims arising out of your User Content, your use
          of the Service, or your violation of these Terms or applicable law.
        </p>
      </LegalSection>

      <LegalSection title="12. Termination">
        <p>
          You may stop using the Service at any time. You may request account deletion as described in our{" "}
          <Link href="/privacy#data-deletion">Privacy Policy</Link>. We may suspend or terminate access for violations
          of these Terms or to protect the Service and users.
        </p>
      </LegalSection>

      <LegalSection title="13. Changes">
        <p>
          We may update these Terms by posting a revised version on this page with an updated effective date. Continued
          use after changes constitutes acceptance.
        </p>
      </LegalSection>

      <LegalSection title="14. Contact">
        <p>
          Purple Merit — Movie Clips
          <br />
          Email: <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>
          <br />
          Related: <Link href="/privacy">Privacy Policy</Link>
        </p>
      </LegalSection>
    </LegalPageShell>
  )
}
